- src/ParameterStage.ts
- src/ZakenApiStack.ts
- src/app/zaken/tests/Statuses.test.ts
- src/app/zaken/tests/openZaakClient.test.ts
- src/app/zaken/tests/requestHandler.test.ts
- src/app/zaken/zaken.lambda.ts
- src/statics.ts
> feat: Add params

- src/app/zaken/Zaken.ts
- src/app/zaken/templates/zaak.mustache
- src/app/zaken/tests/requestHandler.test.ts
> fix: zaak template

- src/app/zaken/Zaken.ts
- src/app/zaken/templates/zaak.mustache
- src/app/zaken/tests/Zaken.test.ts
- Get status types for current zaak
- Sort and get details from possible statuses
- Add to template
> feat: Add status lists to display

- src/app/zaken/zakenRequestHandler.ts
> chore: log session for debugging

- src/app/zaken/templates/zaken.mustache
- src/test.html
> fix: nldesign case design

- src/app/zaken/templates/zaak.mustache
> feat: nlds progress stepper

- src/app/zaken/templates/zaak.mustache
> feat: nlds theme

- src/app/zaken/templates/zaak.mustache
> feat: show date

- src/app/zaken/templates/zaak.mustache
> feat: numbered progress

- src/app/zaken/OpenZaakClient.ts
- src/app/zaken/Zaken.ts
- src/app/zaken/tests/openZaakClient.test.ts
Adds pagination. Should be added to all requests.
> feat: Add pagination to statustypes

- src/ParameterStage.ts
- src/ZakenApiStack.ts
- src/app/zaken/OpenZaakClient.ts
- src/app/zaken/Taken.ts
- src/app/zaken/Zaken.ts
- src/app/zaken/templates/zaak.mustache
- src/app/zaken/tests/Taken.test.ts
- src/app/zaken/tests/Zaken.test.ts
- src/app/zaken/tests/openZaakClient.test.ts
- src/app/zaken/tests/requestHandler.test.ts
- src/app/zaken/tests/samples/taken-by-zaak.json
- src/app/zaken/zaken.lambda.ts
- src/app/zaken/zakenRequestHandler.ts
- src/statics.ts
> feat: Add tasks

- src/app/zaken/OpenZaakClient.ts
> chore: whitespace

- src/ParameterStage.ts
- src/app/zaken/OpenZaakClient.ts
- src/app/zaken/Zaken.ts
> fix: await taken

- src/statics.ts
To prevent Cloudformation from erroring.
Fixes #
> feat: Update secret name

- src/statics.ts
> fix: secret bump

- src/ParameterStage.ts
> fix: secret

- src/ZakenApiStack.ts
> fix: Grant read to objects token

- src/ZakenApiStack.ts
- src/app/zaken/zakenRequestHandler.ts
> fix: Add baseurl to token endpoint

- src/app/zaken/tests/samples/catalogi.json
- src/app/zaken/tests/samples/taken-by-zaak.json
- src/app/zaken/tests/samples/tmp.html
- src/app/zaken/tests/samples/tmp2.html
- src/app/zaken/tests/samples/zaakvoorbeelderror.json
Zit hiermee nog wel in de history, maar gezien de gegevens wat mij betreft geen issue, wel netjes om niet in de main te laten landen.
> chore: remove urls

- src/app/zaken/templates/zaken.mustache
- src/app/zaken/tests/requestHandler.test.ts
- Fix header
- No content-state
- Explainer for incomplete results
> feat: Textual changes

- src/app/zaken/templates/zaken.mustache
- src/shared/Navigation.ts
> feat: menu text

- src/shared/footer.mustache
> feat: Footer update

- src/app/zaken/Zaken.ts
> fix: console.time had no console.timeEnd

- src/app/zaken/Zaken.ts
- src/app/zaken/zaken.lambda.ts
Get openzaak metadata from the lambda handler.
> feat: Reuse openzaak metadata

- package.json
- src/app/zaken/Zaken.ts
- src/app/zaken/tests/Zaken.test.ts
- src/app/zaken/tests/ZakenKvk.test.ts
- src/app/zaken/tests/requestHandler.test.ts
- src/app/zaken/zaken.lambda.ts
- src/app/zaken/zakenRequestHandler.ts
- yarn.lock
- Initialize the zaken object in the lambda handler and reuse it for
subsequent requests.
- Get openzaak metadata from the lambda handler.
- Provide user with each request to zaken: To prepare for reuse/caching of metadata, each request for Zaken
now requires providing the user for this request, instead of keeping this with the constructor.
> feat: Cache metadata

- src/app/zaken/Zaken.ts
- `zaken status` timer vervangen door 3 losse timers
- metadata => for loading metadata
- list zaken -> for list zaken method
- get zaak  -> for get zaak method
> fix: time logging zaken causing errors

- src/app/zaken/Zaken.ts
- src/app/zaken/templates/zaak.mustache
- src/app/zaken/tests/requestHandler.test.ts
- src/app/zaken/zaken.lambda.ts
- src/app/zaken/zakenRequestHandler.ts
- Errors no such label in zaken function fixed (by Marnix)
- Dependencies updated
This PR prevents the errors on production
> fix: update dependencies and no such label fix to production

- package.json
- src/app/zaken/Zaken.ts
- yarn.lock
> feat: release

- src/app/zaken/Taken.ts
- src/app/zaken/tests/Taken.test.ts
- src/app/zaken/tests/samples/taken-by-user.json
> feat: Filter taken by zaak Id

- src/app/zaken/Inzendingen.ts
- src/app/zaken/tests/inzendingen.test.ts
- src/app/zaken/zaken.lambda.ts
- src/app/zaken/zakenRequestHandler.ts
Prepares inzendingen to be handled the same as 'zaken', so listing becomes easier.
> feat: inzendingen as zaken

- src/app/zaken/Inzending.ts
- src/app/zaken/Inzendingen.ts
- src/app/zaken/ZaakConnector.ts
- src/app/zaken/ZaakFormatter.ts
- fix: date submitted always returns from api (but might be fake if unknown)
- fix: Add zaak_type back in inzending-result.
> fix: inzendingen (date + zaak_type)

- src/app/zaken/Taken.ts
- src/app/zaken/Zaken.ts
- src/app/zaken/tests/requestHandler.test.ts
- src/app/zaken/zakenRequestHandler.ts
> chore: Move taken logic to Taken class

- src/app/zaken/Taken.ts
- src/app/zaken/ZaakAggregator.ts
- src/app/zaken/Zaken.ts
- src/app/zaken/tests/requestHandler.test.ts
- src/app/zaken/zaken.lambda.ts
- src/app/zaken/zakenRequestHandler.ts
Eerste stap in refactor zaken-code.
Required for #412
> chore: Move taken logic to Taken class (#413)

- src/app/zaken/Inzendingen.ts
- src/app/zaken/ZaakConnector.ts
- src/app/zaken/ZaakFormatter.ts
- src/app/zaken/Zaken.ts
- src/app/zaken/templates/zaak.mustache
- src/app/zaken/tests/Zaken.test.ts
- src/app/zaken/tests/ZakenKvk.test.ts
- src/app/zaken/tests/zaakformatter.test.ts
Adds a type property to SingleZaak defined as
'case' or 'submission'. This is used in the
template to modify frontend text.
> feat: Add distinguishing property for cases
